language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: hA7Rz0+iiqUE1XkBTto05RybHqVpW7xBHtK8ekExYBxyDeJsLt5VS0rbNfv1hmVwtfW6AHE+HDZfDD3J8bT8gVfqwP5wJfEyb5Ri5+Ovtn0p7RgUgbEwEz7kViLz0YY1DMzWY1hMiqrmG3gCb9WAys4SEjsGZhaW5oQdUeQyr1FWNe587oUDD/Q6eLHItEDwh0wPePOnlexSJ9v6oOg8lOx5Fr7rCyZ3FOQiqyne9dvLK2cAMuEYaI/okK9aj5ymyROKcEXxACry+IviSkeqBzymVZHE85GFtJoUgTN84u5oezpikL8GldY+YL9Y8SSoo4fQTZB7Lg0Jk+rtly1wAbxS4ZnkCq0SMa3CvsHqppO1xYnKuxCz1IXRtF8HeQPL/1RUrEc6bRh2nJk2j5GvqzFzhYUPkYpCn+5OGe6YR6cLKW22EXj3OvF9JwubMHz/PEAjmdAqfz/2J+L7FQ5n8obDcDmDmnJeW1fpUbpq/S0Mt9QvIC/LCqcw43DQJNzCvRRU8Ls+H7t343Nw9ROTDZB3G2d44w7De2Hf2kZj2YRlXHKyI7HjnMgos+qSUJI8AoDzeCGP1S9XqZhMt/xZT7xUbsa1q6iXQJCehGmcgb7ZLsXyt4KUI/SREsuJ62GijCLRO5SVbfmXm7OMC6tJ0t0078g18a/6JHU/hFh4r0E=
  file: target/gnuob-app.war
  skip_cleanup: true
  on:
    tags: true